# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-08 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdmk', models.CharField(max_length=9)),
                ('matkul', models.CharField(max_length=50)),
                ('sks', models.CharField(max_length=1)),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Matkur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdmkr', models.CharField(max_length=9)),
                ('matkur', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdprofesi', models.CharField(max_length=9)),
                ('profesi', models.CharField(max_length=50)),
                ('unitk', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesi_Matkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesi', models.CharField(max_length=50)),
                ('kdmk', models.CharField(max_length=9)),
                ('matkul', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=1)),
                ('presentase', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profesi_Matkur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesi', models.CharField(max_length=50)),
                ('kdmkr', models.CharField(max_length=9)),
                ('matkur', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=1)),
                ('presentase', models.CharField(max_length=2)),
            ],
        ),
    ]
