# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cekprofesi', '0003_remove_matkul_sks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesi_matkul',
            name='matkul',
        ),
        migrations.RemoveField(
            model_name='profesi_matkul',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='profesi_matkur',
            name='matkur',
        ),
        migrations.RemoveField(
            model_name='profesi_matkur',
            name='semester',
        ),
    ]
