# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cekprofesi', '0005_auto_20190816_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesi_matkul',
            name='kdmk',
        ),
        migrations.AddField(
            model_name='profesi_matkul',
            name='kdmk',
            field=models.ManyToManyField(blank=True, to='cekprofesi.Matkul'),
        ),
        migrations.RemoveField(
            model_name='profesi_matkur',
            name='kdmkr',
        ),
        migrations.AddField(
            model_name='profesi_matkur',
            name='kdmkr',
            field=models.ManyToManyField(blank=True, to='cekprofesi.Matkur'),
        ),
    ]
