# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cekprofesi', '0007_auto_20190817_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matkul',
            old_name='kdmk',
            new_name='kdmatkul',
        ),
        migrations.RemoveField(
            model_name='profesi_matkul',
            name='matkul',
        ),
        migrations.AddField(
            model_name='profesi_matkul',
            name='kdmatkul',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cekprofesi.Matkul'),
        ),
    ]
