# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-17 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cekprofesi', '0009_auto_20190817_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matkul',
            old_name='kdmatkul',
            new_name='kdmk',
        ),
    ]
