# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cekprofesi', '0011_auto_20190818_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesi_matkul',
            name='kdmk',
        ),
        migrations.AddField(
            model_name='profesi_matkul',
            name='kdmk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cekprofesi.Matkul'),
        ),
        migrations.RemoveField(
            model_name='profesi_matkur',
            name='kdmkr',
        ),
        migrations.AddField(
            model_name='profesi_matkur',
            name='kdmkr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cekprofesi.Matkur'),
        ),
    ]
