# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cekprofesi', '0012_auto_20190820_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesi_matkul',
            name='kdmk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cekprofesi.Matkul'),
        ),
        migrations.AlterField(
            model_name='profesi_matkur',
            name='kdmkr',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cekprofesi.Matkur'),
        ),
    ]
